# Generated by Django 2.0.7 on 2019-07-22 15:01

from django.db import migrations, models
import django.db.models.deletion
import timetables.models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=200)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Club', verbose_name=users.models.Club)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetables.Day', verbose_name=timetables.models.Day)),
            ],
        ),
    ]
