# Generated by Django 2.0.7 on 2019-07-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='name',
        ),
    ]
