# Generated by Django 2.0.7 on 2019-07-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_auto_20190723_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periods',
            name='time',
        ),
        migrations.AddField(
            model_name='periods',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='periods',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
