# Generated by Django 2.0.7 on 2019-09-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0006_auto_20190906_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periods',
            name='end_time',
            field=models.TimeField(choices=[(1, 'Midnight'), (2, '01 AM'), (3, '02 AM'), (4, '03 AM'), (5, '04 AM'), (6, '05 AM'), (7, '06 AM'), (8, '07 AM'), (9, '08 AM'), (10, '09 AM'), (11, '10 AM'), (12, '11 AM'), (13, 'Noon'), (14, '01 PM'), (15, '02 PM'), (16, '03 PM'), (17, '04 PM'), (18, '05 PM'), (19, '06 PM'), (20, '07 PM'), (21, '08 PM'), (22, '09 PM'), (23, '10 PM'), (24, '11 PM')], null=True),
        ),
        migrations.AlterField(
            model_name='periods',
            name='start_time',
            field=models.TimeField(choices=[(1, 'Midnight'), (2, '01 AM'), (3, '02 AM'), (4, '03 AM'), (5, '04 AM'), (6, '05 AM'), (7, '06 AM'), (8, '07 AM'), (9, '08 AM'), (10, '09 AM'), (11, '10 AM'), (12, '11 AM'), (13, 'Noon'), (14, '01 PM'), (15, '02 PM'), (16, '03 PM'), (17, '04 PM'), (18, '05 PM'), (19, '06 PM'), (20, '07 PM'), (21, '08 PM'), (22, '09 PM'), (23, '10 PM'), (24, '11 PM')], null=True),
        ),
    ]
