# Generated by Django 2.0.7 on 2019-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0007_auto_20190906_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periods',
            name='end_time',
            field=models.TimeField(choices=[(1, '00'), (2, '05'), (3, '10'), (4, '15'), (5, '20')], null=True),
        ),
        migrations.AlterField(
            model_name='periods',
            name='start_time',
            field=models.TimeField(choices=[(1, '00'), (2, '05'), (3, '10'), (4, '15'), (5, '20')], null=True),
        ),
    ]
