# Generated by Django 2.0.7 on 2019-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0009_auto_20190906_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='periods',
            name='end_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='periods',
            name='start_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
