# Generated by Django 2.0.7 on 2019-11-01 15:28

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('timetables', '0010_auto_20190912_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='periods',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Club', verbose_name=users.models.Club),
        ),
    ]
