# Generated by Django 2.0.7 on 2019-06-13 15:35

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190613_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Club', verbose_name=users.models.Club)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
            preserve_default=False,
        ),
    ]
