# Generated by Django 2.0.7 on 2019-06-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190604_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.NullBooleanField(default=False),
        ),
    ]
