# Generated by Django 2.0.7 on 2019-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190609_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='paid',
            field=models.NullBooleanField(default=False),
        ),
    ]
